import { designTokens } from "./design-tokens"

export const lightTheme = {
  background: designTokens.colors.neutral[0],
  foreground: designTokens.colors.neutral[900],
  card: designTokens.colors.neutral[0],
  cardForeground: designTokens.colors.neutral[900],
  popover: designTokens.colors.neutral[0],
  popoverForeground: designTokens.colors.neutral[900],
  primary: designTokens.colors.primary[950],
  primaryForeground: designTokens.colors.neutral[0],
  secondary: designTokens.colors.neutral[100],
  secondaryForeground: designTokens.colors.neutral[900],
  muted: designTokens.colors.neutral[100],
  mutedForeground: designTokens.colors.neutral[500],
  accent: designTokens.colors.neutral[100],
  accentForeground: designTokens.colors.neutral[900],
  destructive: designTokens.colors.error[500],
  destructiveForeground: designTokens.colors.neutral[0],
  border: designTokens.colors.neutral[200],
  input: designTokens.colors.neutral[200],
  ring: designTokens.colors.primary[500],
  success: designTokens.colors.success[500],
  successForeground: designTokens.colors.neutral[0],
  warning: designTokens.colors.warning[500],
  warningForeground: designTokens.colors.neutral[0],
}

export const darkTheme = {
  background: designTokens.colors.neutral[950],
  foreground: designTokens.colors.neutral[50],
  card: designTokens.colors.neutral[950],
  cardForeground: designTokens.colors.neutral[50],
  popover: designTokens.colors.neutral[950],
  popoverForeground: designTokens.colors.neutral[50],
  primary: designTokens.colors.neutral[50],
  primaryForeground: designTokens.colors.neutral[900],
  secondary: designTokens.colors.neutral[800],
  secondaryForeground: designTokens.colors.neutral[50],
  muted: designTokens.colors.neutral[800],
  mutedForeground: designTokens.colors.neutral[400],
  accent: designTokens.colors.neutral[800],
  accentForeground: designTokens.colors.neutral[50],
  destructive: designTokens.colors.error[900],
  destructiveForeground: designTokens.colors.error[50],
  border: designTokens.colors.neutral[800],
  input: designTokens.colors.neutral[800],
  ring: designTokens.colors.neutral[300],
  success: designTokens.colors.success[500],
  successForeground: designTokens.colors.neutral[0],
  warning: designTokens.colors.warning[500],
  warningForeground: designTokens.colors.neutral[0],
}

export type ThemeConfig = typeof lightTheme
